### ISSUE TITLE
A bug of `intensitymap!` for dynamical or frequency-dependent models

### ISSUE THREAD

**Issue by kazuakiyama** [EHTJulia/VLBISkyModels.jl#28]
I found a bug in `intensitymap!` method, which can't be adopted for time/frequency-dependent model. For analytic visibility models, intensitymap! will call `fouriermap` method to map out Fourier space and compute images with FFT. `fouriermap` uses `visibility` function in methods.jl here.
```julia
@inline function visibility(mimg::M, p) where {M}
    #first we split based on whether the model is primitive
    T = typeof(p.U)
    _visibility(isprimitive(M), mimg, p.U, p.V, zero(T), zero(T))
end
```
The issue is that freq and time are zeroed, so it will cause a problem that fully utilize time and freq arguments of `visibility_point(m, u, v, time, freq)`.

**Comment by ptiede** [comment]
This should be fixed more generally now since we restored the old behavior of 
```julia
visibility_point(m, p)
```

However, in general, many of the FFT techniques still don't fully work with frequency-dependent techniques,, so we will leave this open for now.
